version: '3.4'

services:
  identity-server:
    build: ./src/IdentityServer
    ports:
      - '5000:80'
      - '5001:443'
    volumes:
      - ./src/IdentityServer:/root/IdentityServer:cached
      - ./src/IdentityServer/certs:/https/
      - type: bind
        source: ./certs/aspnetapp-root-cert.cer
        target: /https-root/aspnetapp-root-cert.cer
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-identity-server.pfx

  web-api:
    # build: Dockerfile.api
    # # image: web-api
    build:
      context: .
      dockerfile: deployment.api.Dockerfile
    ports:
        - "6000:80"
        - "6001:443"
    volumes:
      - ./src/Api:/root/Api:cached
      - ./src/Api/certs:/https/
    #   - type: bind
    #     source: ./certs/aspnetapp-root-cert.cer
    #     target: /https-root/aspnetapp-root-cert.cer
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=6001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-web-api.pfx